HEADERS1=		\
	HypJac.hpp	\
	HypJacL2.hpp

SOURCES1=		\
	HypJacL2.cu	\
	main.cu

include ../share/Makefile.MAC

HEADERS=$(HEADERS1) $(HEADERS2)
SOURCES=$(SOURCES1) $(SOURCES2)
EXE=x1.exe

all: $(EXE)

$(EXE): $(HEADERS) $(SOURCES) Makefile.MAC ../share/Makefile.MAC
	$(NVCC) $(NVPPFLAGS) $(NVCCFLAGS) $(SOURCES) -o $@ $(NVLDFLAGS)

clean:
	-$(RM) $(EXE)
